### ISSUE TITLE
Is it possible to decode without keeping the entire source file in memory?

### ISSUE THREAD

**Issue by io7m** [ehrmann/j-vcdiff#4]
Hello.

As the title states: Is it possible to apply a diff to a file without having to keep the entire source file in memory? The command line `VCDiffFileBasedCoder` appears to do this, and I can't seem to find anything in the API to avoid doing this. Am I misunderstanding the API?

**Comment by io7m** [comment]
No, it's not possible. The original C implementation can't do it either.

**Comment by ehrmann** [comment]
You're not using the `test` option, are you? I didn't think it had to, but I'd have to read through the code to remember.

**Comment by io7m** [comment]
I'm not, no. It seems that the decoder API always takes a single `byte[]` dictionary. In every example I can find, that dictionary is simply the entirety of the source file read into a byte array. The original C implementation has this note:

https://github.com/google/open-vcdiff/wiki

> This implementation requires that the entire contents of the source file (also known as dictionary file) be loaded into memory. Therefore it cannot handle source files larger than 2-4 GB, depending on the particular restrictions of the OS. The target and delta file sizes do not have this limitation.

There's an unmaintained APL 2.0 Java implementation of the algorithm here that doesn't have that limitation:

https://github.com/kansifang/jvcdiff

It'd be great if the dictionary in `vcdiff-java` could optionally be replaced with a `RandomAccessFile`!

**Comment by ehrmann** [comment]
Ahh, that's what you meant by the source file. Yes, it reads in the entire dictionary.

I'll look into replacing the byte[] with a ByteBuffer. Then you could pass a MappedByteBuffer. What's your use case; are you patching a large file? Do you need it from the command line or as an option in the builder?

**Comment by io7m** [comment]
In my case, it's for downloading and applying patches to large (> 1gb) binary files on Android devices with limited memory and hardware. There's no user interaction, so it's all API.

There'd no doubt be a performance hit, but the algorithm could access the dictionary via an interface:

```
interface Dictionary
{
  byte get(int index);
  void set(int index, byte value);
}
```

That way, I could pass in something that wraps a `byte[]` or a `RandomAccessFile`.

**Comment by ehrmann** [comment]
Can you see if this works in Android? If it does, it'd make the change ~easy. My fear is that it's missing in the Android API or `map` reads the entire file into memory.

```
RandomAccessFile f = ...;
ByteBuffer byteBuffer = f.getChannel().map(MapMode.READ_ONLY, 0, f.length());
```

**Comment by ehrmann** [comment]
Take a look at https://github.com/ehrmann/vcdiff-java/releases/tag/v0.1.1-alpha

The decoders and the decode factory take ByteBuffers, now, so you can pass a mapped ByteBuffer from a RandomAccessFile.

**Comment by io7m** [comment]
I'll give this a shot later today, thanks!

I'm still a little concerned about the memory overhead of this. Mapping a large file into memory obviously won't exhaust the Java heap, but it may still require memory that these devices just don't have (for large files).

**Comment by io7m** [comment]
> My fear is that it's missing in the Android API or map reads the entire file into memory.

I've verified that it's not missing and that it actually does `mmap()` the file: Creating a 1mb file of zeroes, mapping it `MapMode.READ_WRITE`, filling the mapped buffer with `0x10`, and then reading the file with a plain `InputStream` yields a stream of `0x10` values.

It does seem that `MapMode.READ` uses `mmap()` too, as opposed to just reading in the whole file. I've informally verified this by watching the size of the Java heap when mapping a large file.

This is on an API level 25 device (Android 7.1), for the record. I've not checked it on anything older.

**Comment by ehrmann** [comment]
Couple of caveats with mapped buffers:

* Deleting the file is like deleting a file that's a hard link; it won't be gone until the buffer is GCed.
* Forcibly removing the file (like unmounting the FS with the file) causes an error like 
```
java.lang.InternalError: a fault occurred in a recent unsafe memory access operation in compiled Java code
```

But I don't think either of these will be much of an issue for you.

**Comment by ehrmann** [comment]
The ByteBuffer dictionary change is in the 0.1.1 release, so you shouldn't need to worry about the custom build.

**Comment by io7m** [comment]
Thanks for making this change!

I'll give it some testing on some real devices. As I said, it may still be unreasonable to ask some of these small devices to map large files into memory, but maybe we'll be able to get away with it. I've seen reports of some devices refusing to allow (necessarily) contiguous large allocations.
